name: Periodic Dependency Update
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
      - uses: thepwagner/action-update-npm@main
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MY_GITHUB_PAT }}
